replicaCount: 1

image:
  repository: omnivox/gocdb
  tag: latest
  pullPolicy: Always

# The main URL of the GOCDB instance (without the trailing /gocdb)
url: ""

# The default GOCDB scope
defaultScope: ""

# Configure the service of the webserver
service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  hostname: ""
  path: /
  tls: {}
  annotations: {}

# Additional environment variables in the form of a key-value dictionary
env: {}

# Configure the database (uses the official MariaDB charts)
database:
  # The database user credentials to use for the GOCDB
  gocdbUser:
    name: "gocdbuser"
    password: "gocdbpwd"

  # Any SQL data that should be provisioned during deployment; if left empty, the default GOCDB data will be deployed
  data: ""

  # Modify this to match your deployment name: <deployment-name>-database-config
  initdbScriptsConfigMap: gocdb-database-config

  # Default settings overrides
  nameOverride: database

  auth:
    database: ""

  volumePermissions:
    enabled: true

  primary:
    service:
      port: 3306
